# Generated by Django 6.0.6 on 2026-07-02 22:23

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Programming', 'Programming'), ('Design', 'Design'), ('Database', 'Database'), ('AI', 'AI'), ('Blockchain', 'Blockchain'), ('Other', 'Other')], default='Other', verbose_name='Category')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=20, verbose_name='Status')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='Number of likes')),
                ('read_time', models.PositiveIntegerField(default=0, verbose_name='Reading time')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Number of views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-publish',),
                'indexes': [models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx'), models.Index(fields=['-total_likes'], name='blog_post_total_l_6b9c44_idx')],
            },
        ),
    ]
