# Generated by Django 6.0.6 on 2026-07-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=99, verbose_name='Full name')),
                ('email', models.EmailField(max_length=99, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('national_id', models.CharField(max_length=10, verbose_name='National ID Number')),
                ('description', models.TextField(max_length=499, verbose_name='Description')),
                ('resume', models.FileField(upload_to='author_resumes/', verbose_name='Resume')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=9, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, max_length=499, null=True, verbose_name='Reason for rejection')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('reviewed', models.DateTimeField(blank=True, null=True, verbose_name='Review Date')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Lock Date')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_author_requests', to=settings.AUTH_USER_MODEL, verbose_name='Locked by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_author_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_requests', to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Writing Application',
                'verbose_name_plural': 'Writing Requests',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_author_created_c3b83d_idx')],
            },
        ),
    ]
