# Generated by Django 6.0.6 on 2026-07-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_authorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reason_rejected',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for rejection'),
        ),
    ]
